services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: voperituj94jvmfitfi49ug8ghj
      MARIADB_USER: superuser
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: data
    ports: 
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
        DEFAULT_ACCESS_TOKEN: admin-secret-token # <- this is the default access token, generated on first run
    links:
      - mariadb
    ports:
      - "8080:8080"  
    depends_on:
      - mariadb
  bot:
    build: ./discordbot
    container_name: bot
    restart: always
    environment:
        ACCESS_TOKEN: admin-secret-token
    #   BOT_TOKEN: DISCORD_BOT_TOKER
    #   BOT_ACTIVITY: DISCORD_BOT_ACTIVITY ex. playing: <DISCORD_BOT_ACTIVITY>
    links:
      - backend
    depends_on:
      - backend